services:

  postgres_db_for_go_app:
    image: 'bitnami/postgresql:latest'
    container_name: postgres_db_for_go_app
    restart: on-failure
    networks:
      - service
    environment:
      - POSTGRES_DB=test_database
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "test_database"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  go_app_fiber:
    container_name: go_app_fiber
    build:
      context: .
      dockerfile: from_fiber/Dockerfile
    depends_on:
      - postgres_db_for_go_app
    networks:
      - service
    ports:
      - "8000:8000"
    restart: always

  go_app_mux:
    container_name: go_app_mux
    build:
      context: .
      dockerfile: from_mux/Dockerfile
    depends_on:
      - postgres_db_for_go_app
    networks:
      - service
    ports:
      - "8001:8000"
    restart: always

volumes:
  postgres_data:

networks:
  service:
