
services:

  postgres_db_for_go_app:
    image: 'bitnami/postgresql:latest'
    container_name: postgres_db_for_go_app
    restart: on-failure
    networks:
      - service
    environment:
      - POSTGRES_DB=test_database
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    volumes:
      - postgres_data:/bitnami/postgresql

  go_app:
    build: .
    container_name: go_app
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - service
    command: sh -c "[ -f go.mod ] || go mod init go-backend-docker-postgres && go mod tidy && go build -o app main.go && ./app"
    ports:
      - "8000:8000"

volumes:
  postgres_data:

networks:
  service:
